language: node_js

node_js:
  - "lts/*"

branches:
  except:
    - master

script:
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: dist
  target_branch: master
  keep_history: true
  on:
    branch: develop
